name: Build and Publish
# Publish manually
on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  call-build:
    uses: SakiPowered/.github/.github/workflows/shared-gradle-publish.yml@master
    secrets: inherit